# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CodeHub\ProjectCloud\PageUI\addItemDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(739, 490)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.graphwidget = PlotWidget(self.splitter)
        self.graphwidget.setObjectName("graphwidget")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_1.setObjectName("label_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_1)
        self.fileName = QtWidgets.QLineEdit(self.layoutWidget)
        self.fileName.setObjectName("fileName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileName)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.choosePath = QtWidgets.QPushButton(self.layoutWidget)
        self.choosePath.setObjectName("choosePath")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.choosePath)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.regArgs = QtWidgets.QTextEdit(self.layoutWidget)
        self.regArgs.setObjectName("regArgs")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.regArgs)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.mapVisible = QtWidgets.QCheckBox(self.layoutWidget)
        self.mapVisible.setText("")
        self.mapVisible.setObjectName("mapVisible")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.mapVisible)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 1, 1, 1)
        self.label_1.setBuddy(self.fileName)
        self.label_2.setBuddy(self.choosePath)
        self.label_3.setBuddy(self.regArgs)
        self.label_4.setBuddy(self.mapVisible)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_1.setText(_translate("Dialog", "文件名"))
        self.label_2.setText(_translate("Dialog", "文件路径"))
        self.choosePath.setText(_translate("Dialog", "..."))
        self.label_3.setText(_translate("Dialog", "注册参数"))
        self.label_4.setText(_translate("Dialog", "显示拓扑图"))
from pyqtgraph import PlotWidget
