# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CodeHub\CoLoRagent\PageUI\GraphicPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 700)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/color"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphics_global = GraphicWidget(self.centralwidget)
        self.graphics_global.setObjectName("graphics_global")
        self.verticalLayout.addWidget(self.graphics_global)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actiona = QtWidgets.QAction(MainWindow)
        self.actiona.setObjectName("actiona")
        self.actionb = QtWidgets.QAction(MainWindow)
        self.actionb.setObjectName("actionb")
        self.actionc = QtWidgets.QAction(MainWindow)
        self.actionc.setObjectName("actionc")
        self.actiond = QtWidgets.QAction(MainWindow)
        self.actiond.setObjectName("actiond")
        self.toolBar.addAction(self.actiona)
        self.toolBar.addAction(self.actionb)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionc)
        self.toolBar.addAction(self.actiond)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "网络拓扑"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actiona.setText(_translate("MainWindow", "基本信息"))
        self.actiona.setToolTip(_translate("MainWindow", "显示左下框基本信息"))
        self.actionb.setText(_translate("MainWindow", "拓扑修改"))
        self.actionb.setToolTip(_translate("MainWindow", "显示右下框拓扑修改"))
        self.actionc.setText(_translate("MainWindow", "高级通告"))
        self.actionc.setToolTip(_translate("MainWindow", "显示顶部居中高级通告"))
        self.actiond.setText(_translate("MainWindow", "数据通量"))
        self.actiond.setToolTip(_translate("MainWindow", "显示数据通量"))
from GraphicWidget import GraphicWidget
import resource_rc
