# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CodeHub\ProjectCloud\PageUI\mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_horizon = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_horizon.setOrientation(QtCore.Qt.Vertical)
        self.splitter_horizon.setObjectName("splitter_horizon")
        self.tableView = MyTableView(self.splitter_horizon)
        self.tableView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableView.setObjectName("tableView")
        self.listView = MyListView(self.splitter_horizon)
        self.listView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.listView.setObjectName("listView")
        self.splitter_vertical = QtWidgets.QSplitter(self.splitter_horizon)
        self.splitter_vertical.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_vertical.setObjectName("splitter_vertical")
        self.graphics = GraphWidget(self.splitter_vertical)
        self.graphics.setObjectName("graphics")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter_vertical)
        self.tabWidget.setObjectName("tabWidget")
        self.baseTab = QtWidgets.QWidget()
        self.baseTab.setObjectName("baseTab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.baseTab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit = QtWidgets.QTextEdit(self.baseTab)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.tabWidget.addTab(self.baseTab, "")
        self.MoreTab = QtWidgets.QWidget()
        self.MoreTab.setObjectName("MoreTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.MoreTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.MoreTab)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.tabWidget.addTab(self.MoreTab, "")
        self.verticalLayout_2.addWidget(self.splitter_horizon)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(16, 16))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_reg = QtWidgets.QAction(MainWindow)
        self.action_reg.setObjectName("action_reg")
        self.action_undoReg = QtWidgets.QAction(MainWindow)
        self.action_undoReg.setObjectName("action_undoReg")
        self.action_dow = QtWidgets.QAction(MainWindow)
        self.action_dow.setObjectName("action_dow")
        self.action_del = QtWidgets.QAction(MainWindow)
        self.action_del.setObjectName("action_del")
        self.action_hub = QtWidgets.QAction(MainWindow)
        self.action_hub.setObjectName("action_hub")
        self.action_add = QtWidgets.QAction(MainWindow)
        self.action_add.setObjectName("action_add")
        self.action_import = QtWidgets.QAction(MainWindow)
        self.action_import.setObjectName("action_import")
        self.action_openDir = QtWidgets.QAction(MainWindow)
        self.action_openDir.setObjectName("action_openDir")
        self.action_swi = QtWidgets.QAction(MainWindow)
        self.action_swi.setObjectName("action_swi")
        self.action_reset = QtWidgets.QAction(MainWindow)
        self.action_reset.setObjectName("action_reset")
        self.menu.addAction(self.action_import)
        self.menu.addAction(self.action_swi)
        self.menu.addAction(self.action_reset)
        self.menu.addAction(self.action_hub)
        self.menu_2.addAction(self.action_add)
        self.menu_2.addAction(self.action_reg)
        self.menu_2.addAction(self.action_undoReg)
        self.menu_2.addAction(self.action_dow)
        self.menu_2.addAction(self.action_del)
        self.menu_2.addAction(self.action_openDir)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">日志记录</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">--------------------</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.baseTab), _translate("MainWindow", "基本信息"))
        self.label.setText(_translate("MainWindow", "TODO"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.MoreTab), _translate("MainWindow", "更多信息"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_reg.setText(_translate("MainWindow", "通告"))
        self.action_undoReg.setText(_translate("MainWindow", "取消通告"))
        self.action_dow.setText(_translate("MainWindow", "下载"))
        self.action_del.setText(_translate("MainWindow", "删除"))
        self.action_hub.setText(_translate("MainWindow", "仓库目录"))
        self.action_add.setText(_translate("MainWindow", "添加"))
        self.action_import.setText(_translate("MainWindow", "导入数据"))
        self.action_openDir.setText(_translate("MainWindow", "打开文件夹"))
        self.action_swi.setText(_translate("MainWindow", "切换视图"))
        self.action_reset.setText(_translate("MainWindow", "还原视图"))
from GraphWidget import GraphWidget
from serviceList import MyListView
from serviceTable import MyTableView
import resource_rc
