# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\CodeHub\ProjectCloud\PageUI\registerDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 750)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.graphics = GraphWidget(self.splitter)
        self.graphics.setObjectName("graphics")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fileName = QtWidgets.QLabel(self.layoutWidget)
        self.fileName.setObjectName("fileName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fileName)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.filePath = QtWidgets.QLabel(self.layoutWidget)
        self.filePath.setObjectName("filePath")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.filePath)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.fileAddtion = QtWidgets.QLabel(self.layoutWidget)
        self.fileAddtion.setObjectName("fileAddtion")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fileAddtion)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.regArgs = QtWidgets.QTextEdit(self.layoutWidget)
        self.regArgs.setReadOnly(True)
        self.regArgs.setObjectName("regArgs")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.regArgs)
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "文件名"))
        self.fileName.setText(_translate("Dialog", "TextLabel"))
        self.label.setText(_translate("Dialog", "文件路径"))
        self.filePath.setText(_translate("Dialog", "TextLabel"))
        self.label_3.setText(_translate("Dialog", "文件描述"))
        self.fileAddtion.setText(_translate("Dialog", "TextLabel"))
        self.label_4.setText(_translate("Dialog", "注册参数"))
from GraphWidget import GraphWidget
